# ==========================================
# TESTING CONFIGURATION (UNIT TEST)
# ==========================================

# --- Database Configuration (H2 in PostgreSQL Mode) ---
# Mode Memory khusus untuk testing (Cepat & Bersih, meniru sifat Postgres)
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- JPA & Hibernate ---
# Tabel dibuat ulang dari nol setiap kali test suite berjalan
spring.jpa.hibernate.ddl-auto=create-drop
# Matikan log SQL agar terminal tidak penuh saat testing
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# --- SQL Data Initialization ---
# Matikan data.sql saat testing agar environment test benar-benar terisolasi
spring.sql.init.mode=never